### ISSUE TITLE
 -V option to change to one folder stoped to work 

### ISSUE THREAD

**Issue by sergiomb2** [madebr/subdownloader#36]
### Description of problem
./subdownloader.py -d -V /home/sergio/somthing

-V /home/sergio/somthing  is ignored

**Comment by madebr** [comment]
The paths are not ignored.
The gui will search for videos/subtitles in these paths.

It is true that the folder tree will not change to the path which is a deliberate choice.
If multiple paths are passed or a video file is passed, no one directory can be chosen.

**Comment by sergiomb2** [comment]
Hello as a quick note I don't agree with this , if we have a new multipath feature , at least should go to the first path on the list . And as we don't have much man power , we should try keep things simple ... 
I see the same problem for multi languages choices , but when I choose just one language , the drop down list should match with the language in question , which don't show all languages ... 

Best regards

**Comment by sergiomb2** [comment]
hello , sorry for long delay :( , since can be related I write here, the browser tree on left is not updated with selectedfolder nor , selected movie , when we made one selection, the  browser tree should be updated , instead stay as in first run in root , after if we click search subtitles I think this start search all subtitle in my hard drive since start recursively from root directory . 
Cheers

**Comment by sergiomb2** [comment]
as be able to set  browser tree  directory is important ! :)

**Comment by sergiomb2** [comment]
fixed
