### ISSUE TITLE
last commit breaks startup 

### ISSUE THREAD

**Issue by sergiomb2** [madebr/subdownloader#8]
I'm trying fix last commit 
https://github.com/sergiomb2/subdownloader/commit/4ab7fa1a83853e1601a50265521f011513d3063a 

but I stuck, please analyze [1] , I selected Portuguese and Brazilian we got  (<Language:xx=['pt']>, False) and (u'Portuguese (Portugal)', True) in self._search_languages.items() when we should have only one entry with (Language , true) , that is why  lang[0].xxx() raise one error , tuple with true have unicode text instead one Language variable ...

[1]  
[`(<Language:xx=['sq']>, False), (<Language:xx=['ar']>, False), (<Language:xx=['hy']>, False), (<Language:xx=['ms']>, False), (<Language:xx=['bs']>, False), (<Language:xx=['bg']>, False), (<Language:xx=['ca']>, False), (<Language:xx=['eu']>, False), (<Language:xx=['zh']>, False), (<Language:xx=['zh', 'zt']>, False), (<Language:xx=['hr']>, False), (<Language:xx=['cs']>, False), (<Language:xx=['da']>, False), (<Language:xx=['nl']>, False), (<Language:xx=['en']>, False), (<Language:xx=['en']>, False), (<Language:xx=['eo']>, False), (<Language:xx=['et']>, False), (<Language:xx=['fi']>, False), (<Language:xx=['fr']>, False), (<Language:xx=['gl']>, False), (<Language:xx=['ka']>, False), (<Language:xx=['de']>, False), (<Language:xx=['el', 'gr']>, False), (<Language:xx=['he']>, False), (<Language:xx=['hu']>, False), (<Language:xx=['id']>, False), (<Language:xx=['it']>, False), (<Language:xx=['ja']>, False), (<Language:xx=['kk']>, False), (<Language:xx=['ko']>, False), (<Language:xx=['lv']>, False), (<Language:xx=['lt']>, False), (<Language:xx=['lb']>, False), (<Language:xx=['mk']>, False), (<Language:xx=['no']>, False), (<Language:xx=['oc']>, False), (<Language:xx=['fa']>, False), (<Language:xx=['pl']>, False), (<Language:xx=['pt']>, False), (<Language:xx=['pb']>, False), (<Language:xx=['ro']>, False), (<Language:xx=['ru']>, False), (<Language:xx=['sr']>, False), (<Language:xx=['sk']>, False), (<Language:xx=['sl']>, False), (<Language:xx=['es']>, False), (<Language:xx=['sv']>, False), (<Language:xx=['th']>, False), (<Language:xx=['tr']>, False), (<Language:xx=['uk']>, False), (<Language:xx=['vi']>, False), (u'Portuguese (Brazil)', True), (<UnknownLanguage:code=unknown>, False), (u'Portuguese (Portugal)', True)]`

**Comment by madebr** [comment]
I see the problem.
Looks like a difference in behavior between Python 2 and Python 3.
See subdownloader/subdownloader#20

**Comment by sergiomb2** [comment]
```
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/videotreeview.py", line 162, in data
    line += "  " + _("Uploader: %s") % uploader
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/videotreeview.py", line 162, in data
    line += "  " + _("Uploader: %s") % uploader
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)
Aborted (core dumped)
```
with last commits seems that I can choose and filter by 2 languages , now I don't again
